### ISSUE TITLE
Issues building 1.1.1 on F-Droid

### ISSUE THREAD

**Issue by relan** [timo-a/SudoQ#1]
I'm facing two issues compiling 1.1.1 on F-Droid:

1. AndroidX is not enabled while the app uses AndroidX libraries. Please add `android.useAndroidX=true` to the `gradle.properties`.
2. `libs/robotium-solo-4.1.jar` is used, while JARs are prohibited by the F-Droid inclusion policy. Please replace it with a Maven dependency.

**Comment by timo-a** [comment]
Thank you for the report. I published a new release 1.1.1, can you please try again?

**Comment by relan** [comment]
1.1.1 builds for me now, thanks!
